dashboard/dashboard/urls.py
from django.contrib import admin
from django.conf.urls import url, include

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^staff_profile/', include('staff_profile.urls', namespace='staff-profile')),
]

dashboard/staff_profile/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    url(r'^main/$', views.main, name='main'),
    url(r'^profile/(?P<token>[a-z0-9]+)/$', views.get_user_profile, name='profile'),
    url(r'^user/(?P<token>[a-z0-9]+)/$', views.get_logged_in_user, name='user'),
    url(r'^stats/(?P<token>[a-z0-9]+)/$', views.get_employee_stats, name='stats'),
    url(r'^employees/$', views.get_employees, name='employees'),
    url(r'^filtering/(?P<token>[a-z0-9]+)/$', views.filter_employees, name='filtering'),
]

dashboard/staff_profile/models.py
from django.db import models
from django.contrib.auth.models import User


class Employee(models.Model):
    RACE_OPTIONS = (
        ('A', 'African'),
        ('W', 'White'),
        ('I', 'Indian'),
        ('C', 'Coloured'),
        ('O', 'Others'),
    )
    GENDER_OPTIONS = (
        ('M', 'Male'),
        ('F', 'Female'),
    )
    user = models.ForeignKey(User, related_name='employee', blank=True, null=True, on_delete=models.CASCADE)
    id_number = models.CharField(max_length=13, blank=True, null=True)
    phone_number = models.CharField(max_length=10, blank=True, null=True)
    physical_address = models.CharField(max_length=200, blank=True, null=True)
    tax_number = models.CharField(max_length=10, blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    personal_email = models.EmailField(blank=True, null=True)
    github_user = models.CharField(max_length=30, blank=True, null=True)
    birth_date = models.DateTimeField(blank=True, null=True)
    start_date = models.DateTimeField(blank=True, null=True)
    gender = models.CharField(max_length=1, choices=GENDER_OPTIONS, blank=True, null=True)
    race = models.CharField(max_length=1, choices=RACE_OPTIONS, blank=True, null=True)
    creation_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Employee'
        verbose_name_plural = 'Employees'
        ordering = ['-id']

    def __unicode__(self):
        return '%s' % self.user

    @models.permalink
    def get_absolute_url(self):
        return ''

dashboard/staff_profile/views.py
import token

from django.shortcuts import render, redirect
from . import services


def index(request):
    if request.method == 'GET':
        return render(request, 'html/index.html')


def filter_employees(request, token):
    if request.method == 'GET':
        return render(request, 'html/filtering.html', context={'token': token})


def main(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        if username not in ['', None] and password not in ['', None]:
            response = services.login_user(username, password)
            if 'token' in response:
                return render(request, 'html/main.html', response)
            msg = {'success': 'F', 'message': response.get('non_field_errors')[0]}
            return render(request, 'html/index.html', context=msg)
        else:
            msg = {'success': 'F', 'message': 'Username and Password are required'}
            return render(request, 'html/index.html', context=msg)
    else:
        return render(request, 'html/index.html')


def get_user_profile(request, token):
    if request.method == 'GET':
        user_profile = services.get_user_profile(token)
        next_of_kin = user_profile['employee_next_of_kin']
        review = user_profile['employee_review']
        user = user_profile.get('user')
        position = user_profile.get('position')
        employee = {}
        for key in user_profile:
            if key not in ['employee_next_of_kin', 'employee_review', 'user', 'position']:
                employee[key] = user_profile.get(key)
        return render(request, 'html/profile.html',
                      context={'next_of_kin': next_of_kin,
                               'reviews': review,
                               'user': user,
                               'position': position,
                               'employee': employee
                               }
                      )


def get_logged_in_user(request, token):
    user = services.get_logged_in_user(token)
    return render(request, 'html/main.html')


def prepare_filter_query(filter_data):
    filter_query = ''
    for filter_key in filter_data:
        if filter_key not in ['csrfmiddlewaretoken', 'token']:
            if filter_data.get(filter_key) not in ['', None]:
                if filter_key in ['email']:
                    filter_query += '%s__contains=%s&' % (filter_key, filter_data.get(filter_key))
                else:
                    filter_query += '%s=%s&' % (filter_key, filter_data.get(filter_key))

    return filter_query


def get_employees(request):
    if request.method == 'POST':
        employee_filtering_data = request.POST
        token = employee_filtering_data.get('token')
        filter_query = prepare_filter_query(employee_filtering_data)
        employees = services.filter_employees(token, filter_query)
        employee_info_list = []
        for employee in employees:
            employee_data = {}
            for data_key in employee:
                if data_key not in ['github_user']:
                    if data_key not in ['position']:
                        if data_key not in ['user']:
                            employee_data[data_key] = employee[data_key]
                        else:
                            employee_data['first_name'] = employee[data_key].get('first_name')
                            employee_data['last_name'] = employee[data_key].get('last_name')
                    else:
                        position_data = employee[data_key]
                        role = position_data.get('name')
                        level = position_data.get('level')
                        employee_data['name'] = role
                        employee_data['level'] = level

            employee_info_list.append(employee_data)
        return render(request, 'html/list_employees.html', context={'all_employees': employee_info_list})


def get_employee_stats(request, token):
    if request.method == 'GET':
        stats = {}
        employees = services.get_employees(token)
        print employees[0].keys()
        stats['no_of_employees'] = len(employees)
        stats['frontend'] = len(
                [ employee for employee in employees if employee.get('position')['name'] in ['Front-end Developer']])
        stats['backend'] = len(
                [ employee for employee in employees if employee.get('position')['name'] in ['Back-end Developer']])
        stats['projectmanager'] = len(
                [employee for employee in employees if employee.get('position')['name'] in ['Project Manager']])
        stats['gender_male'] = len([employee for employee in employees if employee.get('gender') in ['M']])
        stats['gender_female'] = len([employee for employee in employees if employee.get('gender') in ['F']])
        stats['race_B'] = len([employee for employee in employees if employee.get('race') in ['B']])
        stats['race_C'] = len([employee for employee in employees if employee.get('race') in ['C']])
        stats['race_I'] = len([employee for employee in employees if employee.get('race') in ['I']])
        stats['race_W'] = len([employee for employee in employees if employee.get('race') in ['W']])
        stats['race_N'] = len([employee for employee in employees if employee.get('race') in ['N']])
        return render(request, 'html/statistics.html', context=stats)

dashboard/staff_profile/templates/html/filtering.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Landing Page</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}" type="text/css">
    <script src="{% static 'js/index.js' %}" type="text/javascript"></script>
</head>
<body>
<table>
    <tr>
        <td id="filtering_pane">
            <div id="filter_header"><b>Filter Employees</b></div>
            <form method="post" action="{% url 'staff-profile:employees' %}" >
                {% csrf_token %}
                <select name="gender">
                    <option disabled selected>--Filter by Gender--</option>
                    <option value="F">Female Employees</option>
                    <option value="M">Male Employees</option>
                </select>

                <select name="position">
                <option disabled selected>--Filter by Position--</option>
                <option value="2">Back-End Developer</option>
                <option value="1">Front-End Developer</option>
                <option value="3">Project Manager</option>
                </select>

                <select name="race">
                    <option disabled selected>--Filter by Race--</option>
                    <option value="B">Black African</option>
                    <option value="C">Coloured</option>
                    <option value="I">Indian/Asian</option>
                    <option value="W">White</option>
                    <option value="N">None Dominant</option>
                </select><br>
                <label>Start Date:</label><br>
                <input type="date" name="start_date" placeholder="Start date"><br>
                <label>Birth Date:</label><br>
                <input type="date" name="birth_date" placeholder="Birth date"><br>
                <input type="text" name="user" placeholder="User Id"><br>
                <input type="text" name="email" placeholder="email address"><br>
                <input type="hidden" name="token" value="{{ token }}">
                <input type="submit" value="Filter Employees">
            </form>
        </td>
    </tr>
</table>

</body>
</html>

dashboard/staff_profile/templates/html/index.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Landing Page</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}" type="text/css">
    <script src="{% static 'js/index.js' %}"></script>
</head>
<body>
    <div id="login_page">
        <div id="login_header"><b>Login</b></div>
        <form method="post" action="{% url 'staff-profile:main' %}">
            {% csrf_token %}
            {% if 'F' == success %}
                <label style="color: red"><b>Message:</b> {{ message }}</label><br><br>
            {% endif %}
            <input type="text" name="username" placeholder="Username"><br>
            <input type="password" name="password" placeholder="Password"><br>
            <input type="submit" value="Login">
        </form>
    </div>
</body>
</html>

dashboard/staff_profile/templates/html/list_employees.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Landing Page</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/jquery-ui.min.css' %}" type="text/css">
    <script src="{% static 'js/jquery-ui.min.js' %}" type="text/javascript"></script>

    <link rel="stylesheet" href="{% static 'css/index.css' %}" type="text/css">
    <script src="{% static 'js/index.js' %}" type="text/javascript"></script>
</head>
<body>
<table>
    <tr>
        <td id="right_pane">
            <table>
                <tr id="search">
                    <td colspan="3">
                        <h3>List Of Employees</h3>
                    </td>
                </tr>
                <tr>
                    <td id="e_stats" colspan="3">
                        <ul>
                            {% for employee in all_employees %}
                            <li>
                                <h5 id="emp_title">{{ employee.first_name }} {{ employee.last_name }}</h5>
                                <div id="emp_info">
                                    <label>Gender: {{ employee.gender }}</label><br>
                                    <label>Age: {{ employee.age }}</label><br>
                                    <label>Race: {{ employee.race }}</label><br>
                                    <label>Position: {{ employee.name }}</label><br>
                                    <label>Level: {{ employee.level }}</label><br>
                                    <label>Years Worked: {{ employee.years_worked }}</label><br>
                                    <label>Birth Date: {{ employee.birth_date }}</label><br>
                                    <label>Phone number: {{ employee.phone_number }}</label><br>
                                    <label>Email: {{ employee.email }}</label><br>
                                </div>

                            </li>
                            {% endfor %}
                        </ul>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>

</body>
</html>

dashboard/staff_profile/templates/html/main.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Landing Page</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}" type="text/css">
    <script src="{% static 'js/index.js' %}" type="text/javascript"></script>
</head>
<body>
<table>
    <tr id="search">
        <td>
            <h3>Main Page</h3>
            <a href="{% url 'staff-profile:index' %}" style="float: right;margin-right:15px"><b>Logout</b></a>
        </td>
    </tr>
    <tr>
        <td id="left_pane">
            <ul>
                <li>
                    <a href="{% url 'staff-profile:stats' token %}" >View Statistics</a>
                </li>
                <li>
                    <a href="{% url 'staff-profile:profile' token %}" >View My Profile</a>
                </li>
                <li>
                    <a href="{% url 'staff-profile:filtering' token %}" >View All Employees</a>
                </li>
            </ul>
        </td>

    </tr>
</table>

</body>
</html>

dashboard/staff_profile/templates/html/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Landing Page</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/jquery-ui.min.css' %}" type="text/css">
    <script src="{% static 'js/jquery-ui.min.js' %}" type="text/javascript"></script>

    <link rel="stylesheet" href="{% static 'css/index.css' %}" type="text/css">
    <script src="{% static 'js/index.js' %}" type="text/javascript"></script>
</head>
<body>
<table>
    <tr>
        <td id="right_pane">
            <table>
                <tr id="search">
                    <td colspan="3">
                        <h3>Employee Profile</h3>
                    </td>
                </tr>
                <tr>
                    <td id="e_stats" colspan="3">
                        <ul>
                            <li>
                                <h5 id="emp_title">{{ user.first_name }} {{ user.last_name }}</h5>
                                <div id="emp_info">
                                    <h5>Personal Information</h5>
                                    <label>Id Number: {{ employee.id_number }}</label><br>
                                    <label>Birth Date: {{ employee.birth_date }}</label><br>
                                    <label>Age: {{ employee.age }}</label><br>
                                    <label>Gender: {{ employee.gender }}</label><br>
                                    <label>Race: {{ employee.race }}</label><br>
                                    <label>Phone number: {{ employee.phone_number }}</label><br>
                                    <label>Email: {{ employee.email }}</label><br>

                                    <h5>Next of Kin</h5>
                                    {% for relative in next_of_kin %}
                                        <label>Name: {{ relative.name }}</label><br>
                                        <label>Relationship: {{ relative.relationship }}</label><br>
                                        <label>Phone Number: {{ relative.phone_number }}</label><br>
                                        <label>Email: {{ relative.email }}</label><br>
                                    {% endfor %}

                                    <h5>Job Information</h5>
                                    <label>Position: {{ position.name }}</label><br>
                                    <label>Level: {{ position.level }}</label><br>
                                    <label>Years Worked: {{ employee.years_worked }}</label><br>

                                    <h5>Reviews</h5>
                                    {% for review in reviews %}
                                        {% if review.type == 'P' %}
                                        <label>Type: Performance Increase</label><br>
                                        {% elif review.type == 'S' %}
                                        <label>Type: Starting Salary</label><br>
                                        {% elif review.type == 'A' %}
                                        <label>Type: Annual Increase</label><br>
                                        {% else %}
                                        <label>Type: Expectation Review</label><br>
                                        {% endif %}
                                        <label>Date: {{ review.date }}</label><br>
                                        <label>Salary: {{ review.salary }}</label><br><br>
                                    {% endfor %}

                                </div>
                            </li>
                        </ul>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>

</body>
</html>

dashboard/staff_profile/templates/html/statistics.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Landing Page</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/jquery-ui.min.css' %}" type="text/css">
    <script src="{% static 'js/jquery-ui.min.js' %}" type="text/javascript"></script>

    <link rel="stylesheet" href="{% static 'css/index.css' %}" type="text/css">
    <script src="{% static 'js/index.js' %}" type="text/javascript"></script>
</head>
<body>
<table>
    <tr>
        <td id="right_pane">
            <table>
                <tr id="search">
                    <td colspan="3">
                        <h3>Employees Stats</h3>
                    </td>
                </tr>
                <tr>
                    <td id="e_stats" colspan="3">
                        <ul>
                            <li><label><b></b></label></li>
                            <li>
                                Number of Employees: {{ no_of_employees }}
                            </li>
                        </ul>
                    </td>
                </tr>

                <tr>
                    <td  class="o_stats">
                         <ul>
                            <li><label><b>Position Count:</b></label></li>
                            <li>
                                Back-End Developer: {{ backend }}
                            </li>
                            <li>
                                Front-End Developer: {{ frontend }}
                            </li>
                             <li>
                                Project Manager: {{ projectmanager }}
                            </li>
                        </ul>
                    </td>
                    <td  class="o_stats" >
                         <ul>
                             <li><label><b>Gender Count:</b></label></li>
                            <li>
                                <ul>
                                    <li>Male: {{ gender_male }}</li>
                                    <li>Female: {{ gender_female }}</li>
                                </ul>
                            </li>
                        </ul>
                    </td>
                    <td  class="r_stats" >
                         <ul>
                             <li><label><b>Race Count:</b></label></li>
                            <li>
                                <ul>
                                    <li>Black African: {{ race_B }}</li>
                                    <li>White: {{ race_W }}</li>
                                    <li>Coloured: {{ race_C }}</li>
                                    <li>Indian/Asian: {{ race_I }}</li>
                                    <li>None Dominant: {{ race_N }}</li>
                                </ul>
                            </li>
                        </ul>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>

</body>
</html>